Modules/08_MicrosoftGraph/Demo/MicrosoftGraphWebApp/MicrosoftGraphWebApp/Controllers/GroupsController.cs
using MicrosoftGraphWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MicrosoftGraphWebApp.Controllers {

  [Authorize]
  public class GroupsController : Controller {
    public async Task<ActionResult> Index() {
      List<SiteResponse> sites = await MicrosoftGraphManager.GetGroups();
      return View(sites);
    }
  }

}

Modules/08_MicrosoftGraph/Demo/MicrosoftGraphWebApp/MicrosoftGraphWebApp/Controllers/SitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MicrosoftGraphWebApp.Models;

namespace MicrosoftGraphWebApp.Controllers {

  [Authorize]
  public class SitesController : Controller {

    public async Task<ActionResult> Index() {
      List<SiteResponse> sites = await MicrosoftGraphManager.GetSites();
      return View(sites);
    }

  }
}

Modules/08_MicrosoftGraph/Demo/MicrosoftGraphWebApp/MicrosoftGraphWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Microsoft Graph Web App</title>
  <link href="~/Content/bootstrap.css" rel="stylesheet" />
  <link href="~/Content/App.css" rel="stylesheet" />
</head>

<body>

  <div id="banner" class="container">
    <nav id="topnav" class="navbar navbar-expand-sm navbar-dark bg-dark">
      <ul class="navbar-nav">
        <li class="nav-item active">
          @Html.ActionLink("Microsoft Graph Web App", "Index", "Home",
                            routeValues: null, htmlAttributes: new { @class = "nav-link navbar-brand" })
        </li>
        <li class="nav-item">
          @Html.ActionLink("Users", "Index", "Users",
                           routeValues: null, htmlAttributes: new { @class = "nav-link" })
        </li>
        <li class="nav-item">
          @Html.ActionLink("Applications", "Index", "Applications",
                           routeValues: null, htmlAttributes: new { @class = "nav-link" })
        </li>
        <li class="nav-item">
          @Html.ActionLink("SharePoint Sites", "Index", "Sites",
                           routeValues: null, htmlAttributes: new { @class = "nav-link" })
        </li>

        <li class="nav-item">
          @Html.ActionLink("Office 365 Groups", "Index", "Groups",
                           routeValues: null, htmlAttributes: new { @class = "nav-link" })
        </li>

      </ul>
      @Html.Partial("_LoginPartial")
    </nav>
    @RenderSection("toolbar", required: false)
  </div>

  <!-- Add Main Body Content Here -->
  <div id="content-box" class="container body-content">
    @RenderBody()
  </div>

  <script src="~/Scripts/jquery-3.3.1.js"></script>
  <script src="~/Scripts/jquery.validate.js"></script>
  <script src="~/Scripts/bootstrap.js"></script>
  <script src="~/Scripts/popper.js"></script>

</body>
</html>